### ISSUE TITLE
zrobot can not started in a zeroOS machine 

### ISSUE THREAD

**Issue by Pishoy** [threefoldtech/0-robot#71]
according to ticket in https://support.grid.tf/thread/63
below is zrobot container log for job zrobot
```
In [40]: f = ncl.containers.get('zrobot')

In [41]: job = f.client.subscribe('zrobot')

In [42]: job.stream()
[Tue29 08:52] - .startup.py       :110 :j.zrobot_statup      - INFO     - detect if zdb data repository is configured
[Tue29 08:52] - .startup.py       :114 :j.zrobot_statup      - INFO     - no zdb data repository configuration found
[Tue29 08:52] - .startup.py       :153 :j.zrobot_statup      - INFO     - starting node robot: zrobot server start --mode node --admin-organization green edge cloud.austria.vienna 1 --god --template-repo https://github.com/threefoldtech/0-templates#master
Traceback (most recent call last):
  File "usr/local/bin/zrobot", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/opt/code/github/threefoldtech/0-robot/cmd/zrobot", line 26, in <module>
    entry_point()
  File "/opt/code/github/threefoldtech/0-robot/zerorobot/cli/server.py", line 114, in start
    robot.set_config_repo(config_repo, config_key)
  File "/opt/code/github/threefoldtech/0-robot/zerorobot/robot/robot.py", line 80, in set_config_repo
    config.config_repo = config.ConfigRepo(url=url, key=key)
  File "/opt/code/github/threefoldtech/0-robot/zerorobot/config/config_repo.py", line 21, in __init__
    self._init(url, key)
  File "/opt/code/github/threefoldtech/0-robot/zerorobot/config/config_repo.py", line 68, in _init
    j.tools.configmanager.init(silent=True, configpath=path, keypath=key)
  File "/opt/code/github/threefoldtech/jumpscale_core/Jumpscale/tools/configmanager/IConfigManager.py", line 219, in init
    j.clients.sshkey.key_get(keypath, load=True)
  File "/usr/lib/python3/dist-packages/jumpscale.py", line 1251, in sshkey
    from Jumpscale.clients.sshkey.SSHKeys import SSHKeys as SSHKeys
  File "/opt/code/github/threefoldtech/jumpscale_core/Jumpscale/clients/sshkey/SSHKeys.py", line 1, in <module>
    from .AgentSSHKeys import *
  File "/opt/code/github/threefoldtech/jumpscale_core/Jumpscale/clients/sshkey/AgentSSHKeys.py", line 1, in <module>
    from paramiko.agent import AgentSSH, cSSH2_AGENTC_REQUEST_IDENTITIES, SSH2_AGENT_IDENTITIES_ANSWER, SSHException, AgentKey, Agent
  File "/usr/local/lib/python3.5/dist-packages/paramiko/__init__.py", line 22, in <module>
    from paramiko.transport import SecurityOptions, Transport
  File "/usr/local/lib/python3.5/dist-packages/paramiko/transport.py", line 90, in <module>
    from paramiko.ed25519key import Ed25519Key
  File "/usr/local/lib/python3.5/dist-packages/paramiko/ed25519key.py", line 22, in <module>
    import nacl.signing
  File "/usr/local/lib/python3.5/dist-packages/nacl/signing.py", line 17, in <module>
    import nacl.bindings
  File "/usr/local/lib/python3.5/dist-packages/nacl/bindings/__init__.py", line 17, in <module>
    from nacl.bindings.crypto_aead import (
  File "/usr/local/lib/python3.5/dist-packages/nacl/bindings/crypto_aead.py", line 18, in <module>
    from nacl._sodium import ffi, lib
ImportError: dynamic module does not define module export function (PyInit__sodium)
Out[42]: 5

In [43]: ncl.ping()
Out[43]: 'PONG Version: master @Revision: 9121e2a704f33c5aa5c912079a15689cc3b1a591'

In [44]: ncl
Out[44]: Node <10.102.194.134:6379>

In [45]: ncl.kernel_args
Out[45]: 
{'intel_iommu': 'on',
 'kvm-intel.nested': '1',
 'console': 'tty1',
 'consoleblank': '0',
 'earlyprintk': 'serial,ttyS1,115200n8',
 'loglevel': '7',
 'zerotier': 'c7c8172af1f387a6',
 'organization': '"green',
 'edge': '',
 'cloud.austria.vienna': '',
 '1"': '',
 'support': '',
 'farmer_id': 'token'}

```

**Comment by zaibon** [comment]
as far as I remember this is a bug we never managed to solve. Possible workaround to stop the container and let the node create a new one. If that doesn't work, you can try to reboot the full node.

**Comment by Pishoy** [comment]
issue  fixed by removing zos-0f caching files as seems there are some files are corrupted 
``` rm /var/cache/zerofs/*```
